# Generated by Django 4.0 on 2022-04-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infomodel',
            name='age',
            field=models.IntegerField(max_length=2),
        ),
    ]
